### ISSUE TITLE
Separate URL generation and UI widget into separate repos

### ISSUE THREAD

**Issue by zachleat** [bradvin/social-share-urls#10]
This is an awesome project! I think you’ll get a lot more longevity out of the code if you separate the UI component and the URL generation stuff into separate node modules / repositories though. 

That way someone could still use the URL stuff without needing the UI piece.

Anyway, just a suggestion—feel free to close if you’re not interested in doing that—love the project!

**Comment by bradvin** [comment]
good suggestion @zachleat - would you be interested in helping me separate the projects? I just have zero time to dedicate to any more dev on this

**Comment by HoldOffHunger** [comment]
I would like to take on some more of these requested changes, as well as a few ideas of my own I had.  Have not seen any movement on my last pull request, though.

Personally, I think users like the ReadMe.MD file on this repo more than the generator, so separation isn't terrible (as long as the readme.MD remains sort-of as its "main-page").

**Comment by HoldOffHunger** [comment]
@zachleat: After thinking about it, it's probably wise to keep them in the same repo, but separate the code and the documentation.

While currently only a javascript/html generator is available, it would make sense, naturally, to have generators in other languages as well.

**Comment by HoldOffHunger** [comment]
Code and documentation have been separated.  Readme.MD is now all that there is for documentation (at the top-level), and all code is now in the /code/ dir.  Separated out the JS from the documentation, and also rewrote the JS, added PHP, added Perl, and added ReactJS.

Check it out: https://github.com/bradvin/social-share-urls/tree/master/code

Closing for now.
