### ISSUE TITLE
LinkedIn Link Does Not Seem Right

### ISSUE THREAD

**Issue by chrisbo** [bradvin/social-share-urls#12]
The LinkedIn link doesn't seem right.

Ref: https://developer.linkedin.com/docs/share-on-linkedin > How would you like to Share on LinkedIn? > Customized URL

**Comment by HoldOffHunger** [comment]
Hrm, good point.

We have: https://www.linkedin.com/shareArticle?url={url}&title={title}

We should have: https://www.linkedin.com/shareArticle?mini=true&url={url}&title={title}&summary={desc}&source={provider}

**Comment by HoldOffHunger** [comment]
Solution: https://github.com/bradvin/social-share-urls/pull/13

**Comment by HoldOffHunger** [comment]
Hey, Chrisbo,

Thanks again, your problem should be resolved now, as #13 has been merged into the main branch.  Let me know if you have further issues.

For further info, see: https://github.com/bradvin/social-share-urls/pull/13
