### ISSUE TITLE
Add instagram share

### ISSUE THREAD

**Issue by Surroundpt** [bradvin/social-share-urls#553]
Hi, is it possible to add a share for instagram?

Best regards.

**Comment by hacknug** [comment]
What kind of functionality do you need? https://www.instagram.com/developer/mobile-sharing/iphone-hooks/

**Comment by HoldOffHunger** [comment]
These share links are for things like URL's and text, etc., "This site is great, check it out."  Services like twitter, facebook, etc., love sharing text.

Instagram requires that you have an image to share.  What/how/why are you going to be generating this image?  It might be all the same image, but....why would anyone do that?

**Comment by HoldOffHunger** [comment]
By all means, I am mostly curious.  I guess it could be useful to share artwork of yours on instagram, but, not sure how practical that would be (instagram rules prohibit reposting copyrighted material, etc.).

**Comment by askcreative** [comment]
I would use it to share diy sewing, and crocheting projects. And food 🍰

**Comment by HoldOffHunger** [comment]
@askcreative:

That is the problem.  Are you asking people to share the same exact photo?  Everyone?  You want everyone on instagram to share the same exact photo?  Why would anyone want to do that?

1) Who wants to go from user page to user page, to see the exact same content?
2) You are releasing your rights to owning the image by releasing it on Instagram this way, per terms of use.

From the user's perspective, the idea sounds horrible.  From the creator's perspective, the idea sounds horrible.

You want to use it to share your food?  Why do you need an API for that?  Why can't you use instagram itself?  What about its API helps you share your food in meaningful way to users as viewers, or to you as a creator?

**Comment by askcreative** [comment]
I was thinking along the lines of how one includes optimized images for sharing to Pinterest in a blog or article the same could be done for Instagram.  :pensive:
