### ISSUE TITLE
encodeURIComponent() does not handle -_.!~*'() characters well

### ISSUE THREAD

**Issue by alexkowel** [bradvin/social-share-urls#589]
See here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

The fixed escaping function would be:

```
function fixedEncodeURIComponent(str) {
  return encodeURIComponent(str).replace(/[!'()*]/g, function(c) {
    return '%' + c.charCodeAt(0).toString(16);
  });
}
```

BTW: thank you for this awesome project!

**Comment by HoldOffHunger** [comment]
Ah, very interesting.  Actually, I was unaware of this shortcoming of JavaScript.

I have made the requested change, and tested it myself here: https://jsbin.com/jubacez/edit?html,output

Thanks for bringing this to our attention so we could improve it!
