### ISSUE TITLE
Add Ya.Collections share URL

### ISSUE THREAD

**Issue by web-xaser** [bradvin/social-share-urls#590]
There are additional params for sharing to [Y.Collections](https://collections.yandex.ru/):

- `url` Link to the source page.
- `image` Link to image of the page (required parameter).
- `description` Image description.

So final Y.Collections share URL looks like:

https://yandex.ru/collections/share/?url={url}&image={img}&description={desc}

**Comment by HoldOffHunger** [comment]
We actually don't have any yandex.ru share URL's, only the share URL's for OK.ru, and these do not seem to support the above-listed parameters.

See: https://connect.ok.ru/dk?st.cmd=WidgetSharePreview&st.shareUrl=http://www.wikipedia.com/&description=hello!&image=cool.gif

So, yandex.ru would be a new addition, not a new set of URL parameters, but even then, all I see at a URL with valid parameters is: "Проблемы с доступом к странице" (translation: "Access problems to page").

Going to close this one for now.
