### ISSUE TITLE
Add VK share URL

### ISSUE THREAD

**Issue by inoyakaigor** [bradvin/social-share-urls#6]
http://vk.com/share.php?url={URL}

**Comment by bradvin** [comment]
there is a pull request that is still open that has the following share URL for VK:

http://oauth.vk.com/authorize?client_id=-1&redirect_uri={url}&display=widget&caption={title}

Please can you confirm which one is correct?

**Comment by inoyakaigor** [comment]
@bradvin correct is http://vk.com/share.php?url={URL} **[proof in documentation](https://vk.com/dev/share_details)**

As sample
`https://vk.com/share.php?url=github.com&title=TITLE%20MEANS%20%D0%97%D0%90%D0%93%D0%9B%D0%90%D0%92%D0%98%D0%95&description=%D0%9E%D0%9B%D0%9E%D0%9B%D0%9E%20MEANS%20OLOLO`
gives
![image](https://cloud.githubusercontent.com/assets/1235286/20305755/2319a1dc-ab48-11e6-8792-9aa6c6192e9d.png)

If loggined of course 😉

**Comment by HoldOffHunger** [comment]
Ah, thanks, that is correct.  Checked documentation, looks good.  Made updates, should be good now.

**Comment by bradvin** [comment]
thanks @HoldOffHunger I have merged your changes in

**Comment by FinesseRus** [comment]
@bradvin There are additional params for sharing to VK:

* `url` Link to the page to be posted.
* `title` Post title. If not set, title from the post page will be used.
* `description` Post description. If not set, description from the post page will be used.
* `image`Link to image of the post. If not set, image from the post page will be used.
* `noparse` If true, VK server will not make an additional request to download missing information from the posted page. If false, request will be sent always.
* `no_vk_links` If the value is 1, there will be no active links to VK in the post window.

I suggest to change VK URL to:

```
http://vk.com/share.php?url={url}&title={title}&description={desc}&image={img}
```

Also it would be great if there are links to detailed documentation near the URLs in the readme.

**Comment by MNaz26** [comment]
hmm, okay, but how vk work, when we input url like "te.st/index.php?page=item&id=5"

**Comment by FinesseRus** [comment]
@MNaz26 Encode the url: http://vk.com/share.php?url=http%3A%2F%2Fte.st%2Findex.php%3Fpage%3Ditem%26id%3D5

**Comment by DanielWLam** [comment]
what about m.vk.com/share.php? seems not working in mobile phone
