### ISSUE TITLE
Line sharing not working in android and ios

### ISSUE THREAD

**Issue by Shahjalal7311** [bradvin/social-share-urls#622]
It working on PC. But not working on mobile (IOS, Android). It can't add text when shared line in android and ios.
After click button line shared, auto start line app. Although add text into url. But it none display on line timeline. There is link only.
How can fixed?Please.

**Comment by Shahjalal7311** [comment]
After two days investigate i find the solution in Line sharing with custom text in android and ios
$url = <<<EOF
test comments title
${url}
EOF;
http://line.me/R/msg/text/?<?php echo urlencode($url);?>

This one is work for me.

**Comment by HoldOffHunger** [comment]
Yeap, it seems to be working fine:

http://line.me/R/msg/text/?super-test

I'm going to guess the problem was with the code in question, then.  Going to close this for now.

**Comment by angaloche** [comment]
what was the fix please ?
