### ISSUE TITLE
Is it possible for us to get a callback?

### ISSUE THREAD

**Issue by a455455b** [bradvin/social-share-urls#629]
Is it possible for us to get a share callback?

**Comment by bradvin** [comment]
not sure what you mean?

**Comment by a455455b** [comment]
Sorry, I want to try to receive the return value of each share.

**Comment by HoldOffHunger** [comment]
Hi, a455455b:

Similarly, I'm not sure what you mean.

Clicking a sharelink opens a new tab or browser.  This doesn't return a value in anyway.  If you want to have a JS callback that does this, you can use simple, JavaScript promises.  That seems beyond the scope of what we are doing with this project.

Let me know if this does not help.

**Comment by a455455b** [comment]
Thank you for your answer, there are some omissions in my thinking.

**Comment by romain130492** [comment]
can i get a callback when a user is sharing something?
When the user click on `share`, and really share on his linkedin thread something
thanks
