### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by ryandc** [bradvin/social-share-urls#644]
This works for whatsapp:
`<a href="https://api.whatsapp.com/send?text=www.google.com" data-action="share/whatsapp/share">Share via Whatsapp web</a>`

**Comment by sknorr** [comment]
Whatsapp now has updated documentation describing how to share using the https://wa.me URL (same link).

**Comment by bradvin** [comment]
@sknorr please link to the documentation. I could not find it

**Comment by sknorr** [comment]
Actually, it's just the page linked to from your README, https://faq.whatsapp.com/en/android/26000030/?category=5245251

**Comment by HoldOffHunger** [comment]
Thanks for getting in touch!

We have very stringent requirements on all services we offer, including security.  Fortunately, I am happy to say that WhatApp services now meet this baseline minimum, and have been re-added to the Social Share URLs project again.

This was not an arbitrary exclusion.  Matters of security, user interest, privacy, etc., enter into the thinking of these matters.  But now things seem to be better.

Let me know if more should be done!  Thanks.
