### ISSUE TITLE
LinkedIn Stopped supporting the share url ?

### ISSUE THREAD

**Issue by austriker27** [bradvin/social-share-urls#646]
From the research I've done, it would appear LinkedIn no longer supports the sharing URL and requires Oauth and POST request to generate a post. 

Here's their docs: https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/share-on-linkedin

**Comment by austriker27** [comment]
Follow up - in my testing the linkedin sharing URL does work as of right now however Im not sure when it will be deprecated as the LinkedIn docs dont mention it.

**Comment by HoldOffHunger** [comment]
Ah, interesting!  It seems that actually they now only support the URL parameter, not that the service is down entirely.

https://www.linkedin.com/shareArticle?mini=true&url=google.com&title=111&summary=COOOOOOL!!!!!!!!!!!!

This redirects me automatically to: https://www.linkedin.com/sharing/share-offsite/?url=google.com

Sure, I am already logged in, and generating Oauth post tokens isn't necessary, but, I think that is how most people intend to use social sharing.

But -- I will update the documentation to indicate that only the URL param seems to reflect anything.  This seems reasonable, yes?

**Comment by HoldOffHunger** [comment]
Okay, just pushed a fix for the linkedin change that now only supports the URL param!  Thanks for letting us know!
