### ISSUE TITLE
WhatsApp short link without phone number not working anymore

### ISSUE THREAD

**Issue by Amaimersion** [bradvin/social-share-urls#655]
It is worked earlier: `https://wa.me/?text=text`, but at the moment it is not working anymore.
If i add phone number in this link, then everything is alright: `https://wa.me/8976?text=text`.

This big link `https://api.whatsapp.com/send?text=text` works without phone number.

**Comment by HoldOffHunger** [comment]
Ah, interesting!

Thanks for finding this, I'm going to take a closer look.  I can confirm, wa.me needs the number to work, but api.whatsapp.com does not.  I suspect this is a bug on their part, but it is worth checking out.

Fortunately, we list the good URL first on the doc page, and then the wa.me URL.

**Comment by HoldOffHunger** [comment]
Check this out:

https://stackoverflow.com/questions/56372575/send-message-on-whatsapp-on-whatsapp-web-using-html-or-javascript

>I am using following code but its not working.. https://wa.me/?text=urlencodedtext

Seems like WhatsApp knows, but just doesn't care.  I'll update the docs.

**Comment by Amaimersion** [comment]
It is strange to see such attitude from such big company as Facebook :/

I used `https://wa.me/?text=text` about 9 months ago in my app, and it perfectly worked. Issue on SO addressed 11 months ago. It looks like things on WhatsApp side breaks from time to time, like in any ordinary app (:

>I'll update the docs.

Yes, you definitely should point this in documentation.

**Comment by HoldOffHunger** [comment]
Documentation has been updated!  Thanks again for the info!
