### ISSUE TITLE
LinkedIn share error?

### ISSUE THREAD

**Issue by tommers-walker** [bradvin/social-share-urls#659]
Hi there, using this:
`https://www.linkedin.com/sharing/share-offsite/?url={url}`

I get the LinkedIn error page:
"Something went wrong
Refresh the page"

**Comment by chrisbo** [comment]
You need to replace {url} with a URL encoded URL, e.g. The URL encoded version of https://www.example.com/ is https%3A%2F%2Fwww.example.com%2F

You can access a URL decoding/encoding tool here: https://meyerweb.com/eric/tools/dencoder/

**Comment by tommers-walker** [comment]
Hi Chris, thanks for getting back to me. I should have clarified, I'm not literally using "{url}" - am of course replacing that with an encoded url, but was still landing at the linkedin error page. So for example, https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Fwww.bbc.co.uk%2Fnews
resulted in an error page.

Strangely, it now seems to be working again, so maybe it was just a linkedin issue. Many thanks anyway. Cheers
