### ISSUE TITLE
Unable to star this repo

### ISSUE THREAD

**Issue by zcraber** [bradvin/social-share-urls#670]
Getting error `You can’t perform that action at this time.`
Is anyone else facing this?

**Comment by HoldOffHunger** [comment]
Hrm, no problem for me.

**Comment by ogrodev** [comment]
Star the repo has nothing to do with the project itself so It should not be here as an issue!

**Comment by zcraber** [comment]
> Star the repo has nothing to do with the project itself so It should not be here as an issue!

Ok. I get this error only with this repo. Thus raised the issue here.
