### ISSUE TITLE
Not Able to to open google palus share urls

### ISSUE THREAD

**Issue by sudikrt** [bradvin/social-share-urls#8]
When i open g+ share url, it says error occurred

**Comment by HoldOffHunger** [comment]
I have no problem with Google Plus share links.

I implemented here: www.sortwords.com as a tech-demo.

Opens up just fine for me by this url:
https://plus.google.com/share?url=http%3A%2F%2Fwww.sortwords.com

**Comment by HoldOffHunger** [comment]
I have no problem with Google Plus share links.

I implemented here: www.sortwords.com as a tech-demo.

Opens up just fine for me by this url:
https://plus.google.com/share?url=http%3A%2F%2Fwww.sortwords.com

**Comment by bradvin** [comment]
@sudikrt - can you post an example of the g+ link not working?

I tried @HoldOffHunger 's example and it works 100%

**Comment by sudikrt** [comment]
@bradvin  @HoldOffHunger
Thanks for writing back 
now its working. we are accessing through https:// 
but the site had only http:// protocol
There is a problem with our ssl security certificate now its resolved
