### ISSUE TITLE
[SUGESTION] Remove NewsVine and more...

### ISSUE THREAD

**Issue by subversivo58** [bradvin/social-share-urls#84]
I may be wrong but it seems NewsVine is no longer working.

Possible support for WhatsApp Web depends on browser detection (mobile / browser) see: 

> Strange error (api.whatsapp.com redirect Firefox, Opera, IE and Edge to mobile protocol [whatsapp://])
> https://webapps.stackexchange.com/questions/106145/whatsapp-link-with-phone-number-doesnt-open-whatsapps-web-app

Based on detection: rewrite api.xxx.xxx to web.xxx.xxx (it's work)

In some scenarios the "pop-up" may be blocked ... maybe a "link" option is less blocking.

But this approach has its particularity in Firefox:

> If is Firefox, append to `<body>` before trigger "click" Event
> https://stackoverflow.com/questions/32225904/programmatical-click-on-a-tag-not-working-in-firefox

Add new services:

```javascript
{
    name: 'G-Bookmarks',
    class: 'google',
    url: 'https://www.google.com/bookmarks/mark?op=edit&bkmk={url}&title={title}&annotation={desc}&labels={tags}'
},
{
    name: 'Flattr',
    class: 'flattr',
    url: 'https://flattr.com/submit/auto?user_id={account_id}&url={url}&title={title}'
},
{
    name: 'EchoJS',
    class: 'echojs',
    url: 'http://www.echojs.com/submit?u={url}&t={title}'
},
{
    name: 'Hacker News',
    class: 'hackernews',
    url: 'https://news.ycombinator.com/submitlink?u={url}&t={title}'
},
{
     name: 'Mail',
     class: 'mail',
     url: 'mailto:example@host.com?subject={title}&body={desc}'
}
```

Mobile options like Viber are only effective if they are launched in a "mobile" navigation ... it does not make sense to be available in a "desktop" nagation because they will not lead anywhere (I think).

I did something derived ... if you want to take a look: https://subversivo58.github.io/lab/social-share-link.html

**Comment by HoldOffHunger** [comment]
NewsVine has indeed been shutdown.  Removed it from the list.  Also added the newer links for WhatsApp (which, in fact, were already indicated in the current given source, actually).

Going to look at the newer services tonight.

Thanks a ton for bringing this to my attention.

**Comment by HoldOffHunger** [comment]
EchoJS is a **MASSIVE** security hole, allowing users to login without SSL connections enabled.

This one is going to be skipped for some time for now: https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox?as=u&utm_source=inproduct

I don't feel like endangering anyone who uses my code. =)

**Comment by HoldOffHunger** [comment]
Google Bookmarks, Flattr, Hacker News, and generic web-mail protocol URL's have been added!

Let me know if you have anything further!  Thanks again!!

**Comment by subversivo58** [comment]
Thanks @HoldOffHunger.

Tags can be used on both Twitter (hashtags) and Google Bookmarks (labels).

Some reference documentation and service status

Tumblr share docs: https://www.tumblr.com/docs/en/share_button
Reddit button docs: https://www.reddit.com/buttons/
LiveJournal button docs: https://www.livejournal.com/developer/extshare
Pocket button docs: https://getpocket.com/publisher/button_docs
Flipboard button docs: https://about.flipboard.com/social-plugins/?tool=browser (button to bookmarks bar)

Delicious with: https://delicious.com/ not working ... working this: https://del.icio.us/
Delicious button docs: https://del.icio.us/tools (extracted from code)
Delicious share url example: `https://del.icio.us/save/get_bookmarklet_save?url={}&title={}&notes={}`

Instapaper alternative link: `https://www.instapaper.com/text?u={}` (this auto-search url meta tags)
This extracted from (docs?): https://www.instapaper.com/save (button to bookmarks bar)

FriendFeed with: http://friendfeed.com no working ... this redirect to https://blog.friendfeed.com/ that also does not work :disappointed:

**Comment by HoldOffHunger** [comment]
Oh, will dig into those, too, sometime tonight.  Thanks!

**Comment by HoldOffHunger** [comment]
Add documentation for: Tumblr, Reddit, LiveJournal, Pocket, and Flipboard.

I could not get Delicious to work: https://del.icio.us/save/get_bookmarklet_save?url={url}&title={title}&notes={desc}

Same with friendfeed and instapaper.

Seems like a code issue for delicious.  But friendfeed may have basic HTTPS issues (which, a lot of us have dealt with in the past week or so).  I've removed Delicious and left the others.

Thanks again.  Let me know if you spot anything else.  I couldn't find documentation for EACH parameter, but, I found it for most of them in the links provided.  Been trying to get links for each service hopefully.

**Comment by HoldOffHunger** [comment]
Will re-open if you have anything further, thanks. =)

**Comment by HoldOffHunger** [comment]
Err, I'm going to leave this open until I figure out whether to keep or leave FriendFeed/InstaPaper.

I tried signing up fro these services yesterday, without any luck.  But, today, I'm starting to get some of those email confirmation e-mails, so, I'll check into it again later tonight.

**Comment by subversivo58** [comment]
Delicious seems (at this moment?) Not to be logged in (I have an account at this service) ... it turns out that for now no link is useful for this service :disappointed: 

--------

GetPocket with `https://getpocket.com/save?url={}` redirect to `https://getpocket.com/edit?url={}&url={}` ... is apparently capturing the source reference (origin of the request) by duplicating the **"url"**, I believe it doubles because of the redirection itself

If you use `https://getpocket.com/edit?url={}` the **"url"** parameter is not duplicate

GetPocket accepts parameter **"tags"** that are correctly added to the system, although they do not appear in the interface that is opened

e.g: `https://getpocket.com/edit?url={}&tags={}`

![get-pck-001](https://user-images.githubusercontent.com/6475273/37781696-fa7c23a6-2dcf-11e8-9c2a-104b60aa1334.png)

![get-pck-002](https://user-images.githubusercontent.com/6475273/37781712-ffc36298-2dcf-11e8-9e32-733c9d5c1efa.png)

There is an excerpt in the source that describes that tags should only have alpha-numeric characters:

![get-pck-003](https://user-images.githubusercontent.com/6475273/37782439-9f7bcfea-2dd1-11e8-853d-ab8a314f3bcb.png)

--------

I do not understand your comment about Instapaper?

Instapaper as well as other services needs to be logged, this very comment here on GitHub is captured by the system:

https://www.instapaper.com/text?u=https%3A%2F%2Fgithub.com%2Fbradvin%2Fsocial-share-urls%2Fissues%2F84%23issuecomment-375140139

It extracts information from meta tags and from the content itself

![instapaper-screenshoot](https://user-images.githubusercontent.com/6475273/37776726-b75b67cc-2dc4-11e8-88ca-27f4ece210a0.png)

![instapaper-2](https://user-images.githubusercontent.com/6475273/37778201-1ba4d620-2dc8-11e8-92f2-dc8237e0ecad.png)

------

I was looking at [EchoJS](https://www.echojs.com/) and [Digg](https://digg.com/) and as I see these services do not automatically redirect their stream from port 80 to 443 (secure TLS) but both services use TLS if called on the "https" protocol ... this would not be the case for this library only provide calls on the "https" protocol rather than removelos (or in the case of Digg and others being held)?

EchoJS and Digg examples (with https):

<img alt="digg-001" src="https://user-images.githubusercontent.com/6475273/37785276-897fab06-2dd8-11e8-9246-b5d2b6e8b7e9.png" width="50%"><img alt="echojs-001" src="https://user-images.githubusercontent.com/6475273/37785399-ceb47634-2dd8-11e8-8dbb-54a6936fb1f7.png" width="50%">

In its current support list it seems that Weibo, RenRen, Baidu and Digg do not redirect from 80 to 443

RenRen on "https" has mixed content (load non https)

Baidu (cang.baidu.com/do/add) is apparently not working (neither http nor https)

-------

Some services do not really have documentation about parameters and it is only possible to "discover" these parameters by debugging the source code (widgets, buttons to share, buttons to bookmarklet, ...)

If I have something new I will report on this issue but, I would like to know your opinion: is it the case to only support https?

**Comment by HoldOffHunger** [comment]
Oh, interesting!  InstaPaper works in Chrome, but not FF.

I'm going to double-check that and the others tonight, as well adding the extra sources you've got here (thanks again for those).

**Comment by HoldOffHunger** [comment]
Hey hey,

RE: The new links..

Removed FriendFeed, added InstaPaper Source + tested-by-devs note (with notice about browser compatibility), and updated getPocket from `save` to `edit` (good catch on that one, I had to retest a few times before I really saw the issue).

RE: HTTPS, I would require it for anywhere personally-identifiable information is transferred.  Digg has an interesting setup -- they only allow login through 3rd party apps (like Google), and this transfer seems to be the only place where authentication happens (which forces it to be https at authentication time).  It's really not such a big cost to have this done, and the mathematics behind the authentication mechanism is sound.

Closing for now....let me know if you spot anything more!  Always got my eye open.

Thanks!

**Comment by subversivo58** [comment]
I'm using Firefox 59 and the only thing I got was warnings about Instapaper's own CSP policies, but I did not notice anything different from the service against Google Chrome (or Chromium that I also tested) ... plus the CSP conflict warning only occurred in Firefox itself.

![mz-instapaper](https://user-images.githubusercontent.com/6475273/37808212-018eeec8-2e28-11e8-9c30-cbc677057270.png)

Let me know which FF version you tested?

------

Like Yahoo (compose.mail.yahoo.com), Gmail also has a call: `https://mail.google.com/mail/?view=cm&to={email_address}&su={title}&body={url}`

Apparently `view=cm` defines: view = compose message ... it is also possible to pass the parameters **cc** (Cc) and **bcc** (Cco) (optionally), the **"to"** parameter accepts not only one but a list comma separated

I found this reference in [StackOverflow](https://stackoverflow.com/questions/6548570/url-to-compose-a-message-in-gmail-with-full-gmail-interface-and-specified-to-b#8852679) but I could not find anything in Gmail Api itself

Even with so many networks and existing channels the email is still very used ... I will seek referrals from other popular email services (if there is interest)

**Comment by HoldOffHunger** [comment]
Actually, it was the account-creation part of InstaPaper that was crashing (it was stuck in an infinite captcha loop).  This may have been just a bad way of asking me to confirm my Email Address.

Actually, I am using 56.0.2.  Unfortunately, FF 57.0+ has been completely unstable for development purposes: https://stackoverflow.com/questions/45373290/object-unavailable-in-firefox-console

**Comment by HoldOffHunger** [comment]
Going to reopen this so I can add GMail...

**Comment by HoldOffHunger** [comment]
Just added GMail and reorganized a bit.  There are probably other email services available like this, but I'm not interested in hunting them down one by one. =)
